// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgxp6nFtNiCPhK_4fBZsPYvddAUoAakIs',
    appId: '1:354578488845:web:2fa78d75af36521c55bf44',
    messagingSenderId: '354578488845',
    projectId: 'mushroom-test-84e6f',
    authDomain: 'mushroom-test-84e6f.firebaseapp.com',
    storageBucket: 'mushroom-test-84e6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANzFealYHB3f7VoW2W1jHDz_AQEqfrTY8',
    appId: '1:354578488845:android:ce737a0e5bc58c2455bf44',
    messagingSenderId: '354578488845',
    projectId: 'mushroom-test-84e6f',
    storageBucket: 'mushroom-test-84e6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtu3zY_HA1oqjF-ramrJD0vhJot886sEY',
    appId: '1:354578488845:ios:b996727a184504e355bf44',
    messagingSenderId: '354578488845',
    projectId: 'mushroom-test-84e6f',
    storageBucket: 'mushroom-test-84e6f.appspot.com',
    iosClientId: '354578488845-p4et6417329kodls50li656sjc23u8e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshfungi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtu3zY_HA1oqjF-ramrJD0vhJot886sEY',
    appId: '1:354578488845:ios:b996727a184504e355bf44',
    messagingSenderId: '354578488845',
    projectId: 'mushroom-test-84e6f',
    storageBucket: 'mushroom-test-84e6f.appspot.com',
    iosClientId: '354578488845-p4et6417329kodls50li656sjc23u8e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshfungi',
  );
}
